### ISSUE TITLE
Can not be used normally in leaflet1.3

### ISSUE THREAD

**Issue by gee1k** [alexandre-melard/leaflet.TileLayer.WMTS#19]
Can not be used normally in leaflet1.3

**Comment by dylankolson** [comment]
Whats your issue I may have a fix

**Comment by Trevirirus** [comment]
The problem I Hav and probably @gee1k too is  the following:

> Uncaught Error: Cannot find module 'leaflet-tilelayer-wmts'
>     at Module._resolveFilename (module.js:543:15)
>     at Function.Module._resolveFilename 

I'm using your plugin inside a electron app.

**Comment by Trevirirus** [comment]
Inside the url request there is added a '?' at the begiing of the SERVICE= param. this is crashing my requests
